"""empty message

Revision ID: fd783d613925
Revises: None
Create Date: 2016-08-24 17:24:16.312002

"""

# revision identifiers, used by Alembic.
revision = 'fd783d613925'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'todo', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'todo', 'priority', ['priority_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_constraint(None, 'todo', type_='foreignkey')
    ### end Alembic commands ###
